name: Run NFL Loop

on:
  workflow_dispatch: # Allows you to trigger the entire loop manually with one click

jobs:
  run-loop:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run the script loop
        run: python send_team.py

      - name: Save final empty team list
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add teams.txt
          git diff-index --quiet HEAD || git commit -m "Empty the team list"
          git push

